In [9]:
np.array([1,2,3]).T

array([1, 2, 3])

In [14]:
import numpy as np


a=[114,5]
b=[[1],[2]]

np.dot(a,b)

array([124])

In [15]:
np.matmul(a,b)

array([124])

In [1]:
from sklearn.cross_decomposition import PLSRegression

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

In [3]:
X = iris.data  # we only take the first two features.
y = iris.target

In [4]:
pls = PLSRegression(n_components=2)

In [5]:
pls.fit(X,y)

x
[[1.]]
y
[[1.]]
x
[[1.]]
y
[[1.]]


PLSRegression(copy=True, max_iter=500, n_components=2, scale=True, tol=1e-06)

In [ ]:
pls.x_weights_

In [8]:
pls.transform(X)

array([[-2.26393268,  0.17407526],
       [-2.07797622,  0.15738309],
       [-2.34942383, -0.08607212],
       [-2.2807773 , -0.1638598 ],
       [-2.38301828,  0.04763969],
       [-2.07562175,  0.13076153],
       [-2.41814641, -0.33476031],
       [-2.22856255,  0.10570349],
       [-2.30986624, -0.27235561],
       [-2.18296577,  0.19332419],
       [-2.1763478 ,  0.37526677],
       [-2.31227802, -0.08910385],
       [-2.21414845,  0.14378424],
       [-2.60645734, -0.29144658],
       [-2.22396227,  0.6730778 ],
       [-2.26963508,  0.25898123],
       [-2.20872737,  0.16842518],
       [-2.1862564 ,  0.0949784 ],
       [-1.91722056,  0.52168538],
       [-2.33474899, -0.01565707],
       [-1.92802599,  0.45765451],
       [-2.19648304, -0.06101408],
       [-2.75010765, -0.28547951],
       [-1.80989528, -0.02398335],
       [-2.2124488 , -0.11735158],
       [-1.95292748,  0.23124698],
       [-2.03993357, -0.06190614],
       [-2.17216034,  0.25735506],
       [-2.14484708,