In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
! pip install tensorflow-probability
!pip install tensorflow==2.0.0-beta1

In [3]:
from sklearn import datasets
from sklearn.utils import check_array
import tensorflow as tf
import numpy as np

tf.__version__

/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

'2.0.0-beta1'

In [4]:
iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
Y = iris.target

X = check_array(X, dtype=np.float64,
                ensure_min_samples=2)
Y = check_array(Y, dtype=np.float64,ensure_2d=False)
if Y.ndim == 1:
    Y = Y.reshape(-1, 1)

In [5]:

from sklearn.utils import check_consistent_length

# Check  center scale

In [6]:
from sklearn.cross_decomposition.pls_ import _center_scale_xy
_center_scale_xy(X,Y)[0][:5]

array([[-0.89767388,  1.01560199, -1.33575163, -1.31105215],
       [-1.13920048, -0.13153881, -1.33575163, -1.31105215],
       [-1.38072709,  0.32731751, -1.39239929, -1.31105215],
       [-1.50149039,  0.09788935, -1.27910398, -1.31105215],
       [-1.01843718,  1.24503015, -1.33575163, -1.31105215]])

In [7]:
from pls import _center_scale_xy
Xt = tf.convert_to_tensor(X)
Yt = tf.convert_to_tensor(Y)

_center_scale_xy(Xt,Yt)[0][:5]

<tf.Tensor: id=39, shape=(5, 4), dtype=float64, numpy=
array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])>

## Needs check, probably some stuff

# Check fit method

In [8]:
from sklearn.cross_decomposition import PLSRegression
plsSKLEARN = PLSRegression()
plsSKLEARN.fit(X,Y)

PLSRegression(copy=True, max_iter=500, n_components=2, scale=True, tol=1e-06)

In [43]:
from pls import PLSRegression
Xt = tf.convert_to_tensor(X,dtype=tf.float64)
Yt = tf.convert_to_tensor(Y,dtype=tf.float64)
plsTENSORFLOW = PLSRegression()
plsTENSORFLOW = plsTENSORFLOW.fit(Xt,Yt)

#pls.fit_transform(Xt,Yt)



In [44]:
plsTENSORFLOW.transform(Xt)[:5]

<tf.Tensor: id=2221, shape=(5, 2), dtype=float32, numpy=
array([[-2.2715168 , -0.1746583 ],
       [-2.0849376 , -0.15791023],
       [-2.3572943 ,  0.08636063],
       [-2.2884178 ,  0.16440886],
       [-2.3910015 , -0.04779924]], dtype=float32)>

In [45]:
plsSKLEARN.transform(X)[:5]

array([[-2.26393268,  0.17407526],
       [-2.07797622,  0.15738309],
       [-2.34942383, -0.08607212],
       [-2.2807773 , -0.1638598 ],
       [-2.38301828,  0.04763969]])

In [46]:
plsTENSORFLOW.x_scores_

<tf.Tensor: id=2164, shape=(150, 2), dtype=float32, numpy=
array([[-2.271517  , -0.17465842],
       [-2.0849376 , -0.15791035],
       [-2.3572946 ,  0.08636047],
       [-2.288418  ,  0.16440874],
       [-2.3910017 , -0.04779929],
       [-2.0825753 , -0.1311996 ],
       [-2.4262474 ,  0.3358818 ],
       [-2.2360284 , -0.1060576 ],
       [-2.3176045 ,  0.273268  ],
       [-2.190279  , -0.19397184],
       [-2.1836388 , -0.37652394],
       [-2.3200243 ,  0.08940236],
       [-2.221566  , -0.14426593],
       [-2.6151893 ,  0.29242295],
       [-2.2314126 , -0.67533267],
       [-2.2772386 , -0.25984883],
       [-2.216127  , -0.16898942],
       [-2.1935806 , -0.09529658],
       [-1.9236435 , -0.5234331 ],
       [-2.3425705 ,  0.01570952],
       [-1.9344851 , -0.4591877 ],
       [-2.2038414 ,  0.06121848],
       [-2.7593207 ,  0.2864359 ],
       [-1.8159586 ,  0.02406369],
       [-2.2198608 ,  0.11774472],
       [-1.9594699 , -0.23202167],
       [-2.0467675 ,  0.0621135

In [32]:
Xt

<tf.Tensor: id=1034, shape=(150, 4), dtype=float64, numpy=
array([[-8.97673879e-01,  1.01560199e+00, -1.33575163e+00,
        -1.31105215e+00],
       [-1.13920048e+00, -1.31538812e-01, -1.33575163e+00,
        -1.31105215e+00],
       [-1.38072709e+00,  3.27317509e-01, -1.39239929e+00,
        -1.31105215e+00],
       [-1.50149039e+00,  9.78893485e-02, -1.27910398e+00,
        -1.31105215e+00],
       [-1.01843718e+00,  1.24503015e+00, -1.33575163e+00,
        -1.31105215e+00],
       [-5.35383973e-01,  1.93331463e+00, -1.16580868e+00,
        -1.04866679e+00],
       [-1.50149039e+00,  7.86173830e-01, -1.33575163e+00,
        -1.17985947e+00],
       [-1.01843718e+00,  7.86173830e-01, -1.27910398e+00,
        -1.31105215e+00],
       [-1.74301699e+00, -3.60966973e-01, -1.33575163e+00,
        -1.31105215e+00],
       [-1.13920048e+00,  9.78893485e-02, -1.27910398e+00,
        -1.44224482e+00],
       [-5.35383973e-01,  1.47445831e+00, -1.27910398e+00,
        -1.31105215e+00],
      