In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from sklearn import datasets
from sklearn.utils import check_array
import tensorflow as tf
import numpy as np

tf.__version__

/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

'2.0.0-beta1'

In [3]:
iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
Y = iris.target

X = check_array(X, dtype=np.float64,
                ensure_min_samples=2)
Y = check_array(Y, dtype=np.float64,ensure_2d=False)
if Y.ndim == 1:
    Y = Y.reshape(-1, 1)

In [4]:

from sklearn.utils import check_consistent_length

# Check  center scale

In [5]:
from sklearn.cross_decomposition.pls_ import _center_scale_xy
_center_scale_xy(X,Y)[0][:5]

array([[-0.89767388,  1.01560199, -1.33575163, -1.31105215],
       [-1.13920048, -0.13153881, -1.33575163, -1.31105215],
       [-1.38072709,  0.32731751, -1.39239929, -1.31105215],
       [-1.50149039,  0.09788935, -1.27910398, -1.31105215],
       [-1.01843718,  1.24503015, -1.33575163, -1.31105215]])

In [6]:
from pls import _center_scale_xy
Xt = tf.convert_to_tensor(X)
Yt = tf.convert_to_tensor(Y)

_center_scale_xy(Xt,Yt)[0][:5]

<tf.Tensor: id=39, shape=(5, 4), dtype=float64, numpy=
array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])>

## Needs check, probably some stuff

# Check fit method

In [7]:
from sklearn.cross_decomposition import PLSRegression
pls = PLSRegression()
pls.fit_transform(X,Y)[0][:10]

array([[-2.26393268,  0.17407526],
       [-2.07797622,  0.15738309],
       [-2.34942383, -0.08607212],
       [-2.2807773 , -0.1638598 ],
       [-2.38301828,  0.04763969],
       [-2.07562175,  0.13076153],
       [-2.41814641, -0.33476031],
       [-2.22856255,  0.10570349],
       [-2.30986624, -0.27235561],
       [-2.18296577,  0.19332419]])

In [18]:
from pls import PLSRegression
Xt = tf.convert_to_tensor(X)
Yt = tf.convert_to_tensor(Y)
pls = PLSRegression()
pls.fit_transform(Xt,Yt)[0][:10]

#pls.fit_transform(Xt,Yt)



NameError: name 'np' is not defined