In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#! pip install tensorflow-probability
#!pip install tensorflow==2.0.0-beta1

In [3]:
from sklearn import datasets
from sklearn.utils import check_array
import tensorflow as tf
import numpy as np

tf.__version__

'2.0.0-alpha0'

In [4]:
iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
Y = iris.target

X = check_array(X, dtype=np.float64,
                ensure_min_samples=2)
Y = check_array(Y, dtype=np.float64,ensure_2d=False)
if Y.ndim == 1:
    Y = Y.reshape(-1, 1)

In [5]:

from sklearn.utils import check_consistent_length

# Check  center scale

In [6]:
from sklearn.cross_decomposition.pls_ import _center_scale_xy
_center_scale_xy(X,Y)[0][:5]

array([[-0.89767388,  1.01560199, -1.33575163, -1.31105215],
       [-1.13920048, -0.13153881, -1.33575163, -1.31105215],
       [-1.38072709,  0.32731751, -1.39239929, -1.31105215],
       [-1.50149039,  0.09788935, -1.27910398, -1.31105215],
       [-1.01843718,  1.24503015, -1.33575163, -1.31105215]])

In [7]:
from pls import _center_scale_xy
Xt = tf.convert_to_tensor(X)
Yt = tf.convert_to_tensor(Y)

_center_scale_xy(Xt,Yt)[0][:5]

W0904 11:05:31.819932 4623410624 tf_logging.py:161] Entity <function _center_scale_xy at 0x1a2fbd2950> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function _center_scale_xy at 0x1a2fbd2950>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: name 'tf' is not defined


<tf.Tensor: id=59, shape=(5, 4), dtype=float64, numpy=
array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])>

## Needs check, probably some stuff

# Check fit method

In [8]:
from sklearn.cross_decomposition import PLSRegression
plsSKLEARN = PLSRegression()
plsSKLEARN.fit(X,Y)

PLSRegression(copy=True, max_iter=500, n_components=2, scale=True, tol=1e-06)

In [9]:
from pls import PLSRegression
Xt = tf.convert_to_tensor(X,dtype=tf.float64)
Yt = tf.convert_to_tensor(Y,dtype=tf.float64)
plsTENSORFLOW = PLSRegression()
plsTENSORFLOW = plsTENSORFLOW.fit(Xt,Yt)

#pls.fit_transform(Xt,Yt)



### Check transform

In [10]:
plsTENSORFLOW.transform(Xt,Yt)[0][:5]

W0904 11:05:32.233129 4623410624 tf_logging.py:161] Entity <bound method _PLS.transform of <tensorflow.python.eager.function.TfMethodTarget object at 0x10eb18b70>> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <bound method _PLS.transform of <tensorflow.python.eager.function.TfMethodTarget object at 0x10eb18b70>>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: name 'tf' is not defined


<tf.Tensor: id=354, shape=(5, 2), dtype=float32, numpy=
array([[-2.2715173 , -0.17465845],
       [-2.0849378 , -0.15791035],
       [-2.3572946 ,  0.08636039],
       [-2.2884183 ,  0.16440868],
       [-2.3910017 , -0.04779935]], dtype=float32)>

In [11]:
plsSKLEARN.transform(X,Y)[0][:5]

array([[-2.26393268,  0.17407526],
       [-2.07797622,  0.15738309],
       [-2.34942383, -0.08607212],
       [-2.2807773 , -0.1638598 ],
       [-2.38301828,  0.04763969]])

### Check pls attributes

In [12]:
plsSKLEARN.x_scores_[:5]

array([[-2.26393268,  0.17407526],
       [-2.07797622,  0.15738309],
       [-2.34942383, -0.08607212],
       [-2.2807773 , -0.1638598 ],
       [-2.38301828,  0.04763969]])

In [13]:
plsTENSORFLOW.x_scores_[:5]

<tf.Tensor: id=359, shape=(5, 2), dtype=float64, numpy=
array([[-2.27151707, -0.17465842],
       [-2.08493764, -0.15791034],
       [-2.35729462,  0.08636047],
       [-2.28841811,  0.16440875],
       [-2.39100162, -0.04779929]])>

In [18]:
plsSKLEARN.x_rotations_[:5]

array([[ 0.48438504,  0.76758179],
       [-0.26408993, -0.14706064],
       [ 0.58742778, -0.16621892],
       [ 0.59207791, -0.60290604]])

In [19]:
plsTENSORFLOW.x_rotations_[:5]

<tf.Tensor: id=648, shape=(4, 2), dtype=float64, numpy=
array([[ 0.48438504, -0.76758179],
       [-0.26408993,  0.14706064],
       [ 0.58742778,  0.16621892],
       [ 0.59207791,  0.60290604]])>

### Check predict

In [14]:
plsSKLEARN.predict(X)[:5]

array([[-1.33501112],
       [-1.2242657 ],
       [-1.26404865],
       [-1.19057216],
       [-1.34353101]])

In [15]:
plsTENSORFLOW.predict(Xt)[:5]

W0904 11:05:32.588355 4623410624 tf_logging.py:161] Entity <bound method _PLS.predict of <tensorflow.python.eager.function.TfMethodTarget object at 0x1a302387f0>> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <bound method _PLS.predict of <tensorflow.python.eager.function.TfMethodTarget object at 0x1a302387f0>>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: name 'tf' is not defined


<tf.Tensor: id=379, shape=(5, 1), dtype=float64, numpy=
array([[-1.33501112],
       [-1.2242657 ],
       [-1.26404865],
       [-1.19057216],
       [-1.34353101]])>

### Check fit_transform

In [16]:
plsSKLEARN.fit_transform(X,Y)[0][:5]

array([[-2.26393268,  0.17407526],
       [-2.07797622,  0.15738309],
       [-2.34942383, -0.08607212],
       [-2.2807773 , -0.1638598 ],
       [-2.38301828,  0.04763969]])

In [17]:
plsTENSORFLOW.fit_transform(X,Y)[0][:5]

<tf.Tensor: id=643, shape=(5, 2), dtype=float32, numpy=
array([[-2.2715173 , -0.17465845],
       [-2.0849378 , -0.15791035],
       [-2.3572946 ,  0.08636039],
       [-2.2884183 ,  0.16440868],
       [-2.3910017 , -0.04779935]], dtype=float32)>