In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
! pip install tensorflow-probability
!pip install tensorflow==2.0.0-beta1

In [3]:
from sklearn import datasets
from sklearn.utils import check_array
import tensorflow as tf
import numpy as np

tf.__version__

/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

'2.0.0-beta1'

In [4]:
iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
Y = iris.target

X = check_array(X, dtype=np.float64,
                ensure_min_samples=2)
Y = check_array(Y, dtype=np.float64,ensure_2d=False)
if Y.ndim == 1:
    Y = Y.reshape(-1, 1)

In [5]:

from sklearn.utils import check_consistent_length

# Check  center scale

In [6]:
from sklearn.cross_decomposition.pls_ import _center_scale_xy
_center_scale_xy(X,Y)[0][:5]

array([[-0.89767388,  1.01560199, -1.33575163, -1.31105215],
       [-1.13920048, -0.13153881, -1.33575163, -1.31105215],
       [-1.38072709,  0.32731751, -1.39239929, -1.31105215],
       [-1.50149039,  0.09788935, -1.27910398, -1.31105215],
       [-1.01843718,  1.24503015, -1.33575163, -1.31105215]])

In [7]:
from pls import _center_scale_xy
Xt = tf.convert_to_tensor(X)
Yt = tf.convert_to_tensor(Y)

_center_scale_xy(Xt,Yt)[0][:5]

<tf.Tensor: id=39, shape=(5, 4), dtype=float64, numpy=
array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])>

## Needs check, probably some stuff

# Check fit method

In [8]:
from sklearn.cross_decomposition import PLSRegression
plsSKLEARN = PLSRegression()
plsSKLEARN.fit(X,Y)

PLSRegression(copy=True, max_iter=500, n_components=2, scale=True, tol=1e-06)

In [25]:
from pls import PLSRegression
Xt = tf.convert_to_tensor(X)
Yt = tf.convert_to_tensor(Y)
plsTENSORFLOW = PLSRegression()
plsTENSORFLOW = plsTENSORFLOW.fit(Xt,Yt)

#pls.fit_transform(Xt,Yt)



W0901 18:06:53.866118 140654431446848 deprecation.py:323] From /opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/math/linalg.py:432: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


(4, 1)
(4, 1)


In [26]:
plsTENSORFLOW.x_loadings_

<tf.Tensor: id=2272, shape=(4, 2), dtype=float32, numpy=
array([[ 0.5190693 , -0.9406599 ],
       [-0.2710662 , -0.3501131 ],
       [ 0.58125526,  0.09345418],
       [ 0.5667147 ,  0.5206792 ]], dtype=float32)>

In [24]:
plsSKLEARN.x_loadings_

array([[ 0.51906934,  0.94065986],
       [-0.27106618,  0.35011308],
       [ 0.58125524, -0.09345418],
       [ 0.56671471, -0.52067918]])

In [27]:
plsTENSORFLOW.x_rotations_

<tf.Tensor: id=2301, shape=(4, 2), dtype=float32, numpy=
array([[ 0.48438495, -0.7675818 ],
       [-0.26408988,  0.14706065],
       [ 0.58742774,  0.1662189 ],
       [ 0.5920779 ,  0.602906  ]], dtype=float32)>

In [28]:
plsSKLEARN.x_rotations_

array([[ 0.48438504,  0.76758179],
       [-0.26408993, -0.14706064],
       [ 0.58742778, -0.16621892],
       [ 0.59207791, -0.60290604]])